# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('styles.py', '.'), ('api_client.py', '.')],
    hiddenimports=[
        'PyQt6', 
        'PyQt6.QtCore', 
        'PyQt6.QtWidgets', 
        'PyQt6.QtGui', 
        'requests',
        # Новые для PDF и отчётов
        'PyPDF2',
        'jinja2',
        'jinja2.runtime',
        'jinja2.loaders',
        'weasyprint',
        'weasyprint.urls',
        'bs4',
        'bs4.builder',
        'lxml',
        'lxml.etree',
        'lxml.html',
        'httpx',
        'httpx.client',
        'PIL',
        'PIL.Image',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='CompetitorMonitor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)